apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: consul
  namespace: consul-system
spec:
  chart:
    spec:
      version: ">=1.6.2"
  values:
    global:
      name: consul-nexus
      metrics:
        enabled: true
    client:
      enabled: true
    server:
      enabled: true
      replicas: 1
      storageClass: local-path
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
    ui:
      enabled: true
      service:
        enabled: true
        type: ClusterIP
        annotations: |
          consul.hashicorp.com/service-sync: "true"
          consul.hashicorp.com/service-tags: "traefik.enable=true,traefik.http.routers.consul-ui.entrypoints=websecure-int,traefik.http.routers.consul-ui.rule=Host(`consul.sajbox.com`)"
    connectInject:
      enabled: true
      default: false
    syncCatalog:
      enabled: true
      default: false
      toConsul: true
      toK8S: false
