apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base/local-path-provisioner
  - ../_base/consul
  - ../_base/traefik
patches:
  - path: consul-values.yaml
    target:
      kind: HelmRelease
      name: consul
  - path: traefik-values.yaml
    target:
      kind: HelmRelease
      name: traefik
