apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base/local-path-provisioner
  - ../_base/consul
  - ../_base/traefik
patchesStrategicMerge:
  - consul-values.yaml
  - traefik-values.yaml
