apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base/local-path-provisioner
  - ../_base/secrets-csi
  - ../_base/consul
  - ../_base/vault
  - ../_base/traefik
  - ../_base/podinfo

patches:
  - path: consul-values.yaml
    target:
      kind: HelmRelease
      name: consul
  - path: vault-values.yaml
    target:
      kind: HelmRelease
      name: vault
  - path: vault-secrets-operator-values.yaml
    target:
      kind: HelmRelease
      name: vault-secrets-operator
  - path: traefik-values.yaml
    target:
      kind: HelmRelease
      name: traefik
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: podinfo
