apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_base/local-path-provisioner
  - ../_base/secrets-csi
  - ../_base/vault
  - ../_base/podinfo

patches:
  - path: vault-values.yaml
    target:
      kind: HelmRelease
      name: vault
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: podinfo
