apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart:
    spec:
      version: ">=34.4.1"
  values:
    additionalArguments:
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.endpoint.address=consul-nexus-server.consul.svc.cluster.local:8500"
      - "--providers.consulcatalog.exposedByDefault=false"
      - "--providers.consulcatalog.connectAware=true"
      - "--providers.consulcatalog.connectByDefault=true"
    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
