apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart:
    spec:
      version: ">=34.4.1"
  values:
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.sajbox.com`)
        entryPoints: ["websecure-internal"]
    service:
      annotations:
        consul.hashicorp.com/service-sync: "true"
      additionalServices:
        internal:
          consul.hashicorp.com/service-sync: "true"
    ports:
      websecure-int:
        port: 9443
        exposedPort: 443
        protocol: TCP
        expose:
          default: false
          internal: true
        tls:
          enabled: true
    additionalArguments:
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.endpoint.address=consul-nexus-server.consul-system.svc.cluster.local:8500"
      - "--providers.consulcatalog.endpoint.scheme=http"
      - "--providers.consulcatalog.exposedByDefault=false"
      - "--providers.consulcatalog.connectAware=true"
      - "--providers.consulcatalog.connectByDefault=true"
