apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart:
    spec:
      version: ">=34.4.1"
  values:
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.int.sajbox.com`)
        entryPoints: ["websecure"]
    additionalArguments:
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.defaultRule=Host(`{{ .Name }}.saj.sh`)"
      - "--providers.consulcatalog.endpoint.address=consul-nexus-server.consul-system.svc.cluster.local:8500"
      - "--providers.consulcatalog.endpoint.scheme=http"
      - "--providers.consulcatalog.exposedByDefault=false"
      - "--providers.consulcatalog.connectAware=true"
      - "--providers.consulcatalog.connectByDefault=true"
