apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-system
spec:
  chart:
    spec:
      version: ">=0.10.0"
  values:
    controller:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "vault-active:8200"
    defaultVaultConnection:
      enabled: true
      address: "http://localhost:8200"
      skipTLSVerify: true
    defaultAuthMethod:
      enabled: true
      allowedNamespaces:
        - "*"
      kubernetes:
        role: "nexus"
        tokenAudiences:
          - "vault"
