apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault-system
spec:
  chart:
    spec:
      version: ">=0.29.1"
  values:
    server:
      affinity: ""
      ha:
        enabled: true
