apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault-system
spec:
  chart:
    spec:
      version: ">=0.29.1"
  values:
    global:
      enabled: true
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
          cpu: 250m
    server:
      affinity: ""
      ha:
        enabled: true
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "vault"
        consul.hashicorp.com/service-tags: "\
          traefik.enable=true,\
          traefik.http.routers.podinfo.entrypoints=websecure,\
          traefik.http.routers.podinfo.rule=Host(`vault.saj.sh`)"
