apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-system
spec:
  chart:
    spec:
      version: ">=0.10.0"
  values:
    defaultVaultConnection:
      enabled: true
      address: "http://vault.service.dc1.consul:8200"
      skipTLSVerify: true
    defaultAuthMethod:
      enabled: true
      allowedNamespaces:
        - "*"
      kubernetes:
        role: "nexus"
        tokenAudiences:
          - "vault"
    annotations:
      consul.hashicorp.com/connect-inject: "true"
