apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: consul
  namespace: consul-system
spec:
  releaseName: consul
  chart:
    spec:
      chart: consul
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    global:
      name: consul
