apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-csi
  namespace: secrets-csi-system
spec:
  releaseName: secrets-csi
  chart:
    spec:
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: secrets-csi
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    syncSecret:
      enabled: true
