apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-ha
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: redis
      version: "20.2.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  targetNamespace: redis-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Simplified architecture for homelab
    architecture: standalone

    # Authentication
    auth:
      enabled: true
      existingSecret: "redis-credentials"
      existingSecretPasswordKey: "password"

    # Master configuration
    master:
      # Resource limits for homelab
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

      # Persistence
      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 8Gi

      # Service configuration
      service:
        type: ClusterIP
        ports:
          redis: 6379

    # Redis configuration - simplified
    commonConfiguration: |-
      # Basic Redis configuration
      save 900 1
      save 300 10
      save 60 10000
      tcp-keepalive 60
      maxmemory-policy allkeys-lru

    # Volume permissions (for Longhorn)
    volumePermissions:
      enabled: true
      securityContext:
        runAsUser: 0

    # Metrics (disable for homelab)
    metrics:
      enabled: false

    # Network policy (optional)
    networkPolicy:
      enabled: false

    # Service account
    serviceAccount:
      create: true
      automountServiceAccountToken: false
