apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql-ha
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql-ha
      version: "14.2.32"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  targetNamespace: postgresql-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Global settings
    global:
      postgresql:
        # These will be overridden by External Secrets
        username: "postgres"
        database: "postgres"
      storageClass: "longhorn"

    # PostgreSQL settings
    postgresql:
      replicaCount: 2 # Primary + 1 replica for 2-node setup

      # Resource limits for homelab
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi

      # Pod anti-affinity to spread across nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: postgresql-ha
                  app.kubernetes.io/component: postgresql
              topologyKey: kubernetes.io/hostname

      # Persistence
      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 20Gi

      # Security context
      securityContext:
        enabled: true
        fsGroup: 1001
        runAsUser: 1001

      # Network policy (optional)
      networkPolicy:
        enabled: false

      # Use default PostgreSQL configuration for now

    # PgPool settings for connection pooling and load balancing
    pgpool:
      replicaCount: 2

      # Resource limits
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

      # Pod anti-affinity
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: postgresql-ha
                    app.kubernetes.io/component: pgpool
                topologyKey: kubernetes.io/hostname

    # Persistence for PgPool
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 2Gi

    # Service configuration
    service:
      type: ClusterIP
      port: 5432

    # Metrics (enable if you have monitoring)
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

    # External secrets integration
    auth:
      existingSecret: "postgresql-credentials"
      secretKeys:
        adminPasswordKey: "postgres-password"
        replicationPasswordKey: "repmgr-password"

    # Volume permissions (for Longhorn)
    volumePermissions:
      enabled: true
      securityContext:
        runAsUser: 0

    # Init scripts (can be used for database initialization)
    initdbScripts: {}
