---
# THIS FILE CONTAINS SECRETS - DO NOT COMMIT TO GIT
# Apply this file manually with: kubectl apply -f authentik-secrets-fixed.yaml
#
apiVersion: v1
kind: Secret
metadata:
  name: authentik-helm-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |
    authentik:
      # IMPORTANT: This is a secure secret key - keep it safe!
      # This is used for cookie signing and unique user IDs
      # DO NOT CHANGE after first install
      secret_key: "98fe7b780e4f14763510251986583fb41cc60fc92b503652fd166fa449894886be639ff7abe75cae18d4e0259e84431bfcb6"

      postgresql:
        # Password for the authentik PostgreSQL user
        password: "1b097b8442483e278c84023e055b50f9f2abead042730d948e45ae1578a33f21"

      redis:
        # Password for Redis (optional, can leave empty for internal Redis)
        password: ""

      email:
        # Configure if you want email functionality
        # host: "smtp.example.com"
        # port: 587
        # username: "your-email@example.com"
        # password: "your-smtp-password"
        # use_tls: true
        # from: "authentik <noreply@example.com>"

    # PostgreSQL admin and user passwords
    postgresql:
      auth:
        # Password for the 'authentik' database user
        password: "1b097b8442483e278c84023e055b50f9f2abead042730d948e45ae1578a33f21"
        # Password for the 'postgres' admin user
        postgresPassword: "0c23be20ced8e780a991c133243de286c15d36ab9e9e52b362447d4f25cba1ce"

    # Redis password (if you want to enable auth)
    redis:
      auth:
        enabled: false
        password: ""
