apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: postgresql-system
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        postgres-password: "{{ .password }}"
        repmgr-password: "{{ .repmgrPassword }}"
  data:
    - secretKey: password
      remoteRef:
        key: database/postgresql
        property: password
    - secretKey: repmgrPassword
      remoteRef:
        key: database/postgresql
        property: repmgr-password
