apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: authentik
      version: "2025.6.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
  releaseName: authentik
  targetNamespace: authentik-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: warn
  values:
    authentik:
      postgresql:
        host: postgresql-cluster-rw.postgres-system.svc.cluster.local
        port: 5432
        name: authentik
    postgresql:
      enabled: false
    redis:
      enabled: true
    server:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
    worker:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 512Mi
  valuesFrom:
    - kind: Secret
      name: authentik-postgresql-credentials-flux
      valuesKey: username
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-postgresql-credentials-flux
      valuesKey: password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets-flux
      valuesKey: secret_key
      targetPath: authentik.secret_key
