apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: istio
spec:
  controllerName: istio.io/gateway-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ext-gateway-options
  namespace: gateway-api-system
data:
  service: |
    metadata:
      annotations:
        metallb.universe.tf/address-pool: external-pool
    spec:
      type: LoadBalancer
      externalTrafficPolicy: Local
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ext-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: ext-gateway-options
  listeners:
    - name: http
      hostname: "*.saj.sh"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      hostname: "*.saj.sh"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-saj-sh-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
