apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-media-control
  namespace: go-media-control-system
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: go-media-control
  template:
    metadata:
      labels:
        pod: go-media-control
    spec:
      containers:
        - image: ghcr.io/git-saj/go-media-control:sha-cb18460
          name: go-media-control
          envFrom:
            - secretRef:
                name: go-media-control-env
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /tv/health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /tv/health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-media-control
  namespace: go-media-control-system
spec:
  selector:
    pod: go-media-control
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
