apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: longhorn
      version: ">=1.9.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  releaseName: longhorn
  targetNamespace: longhorn-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: warn
  values:
    # Replica settings (set to 2 for availability on 2 nodes; avoids scheduling failures)
    defaultSettings:
      defaultReplicaCount: 2
      defaultDataPath: "/var/lib/longhorn" # Use large disk; ensure mounted if needed

    # Persistence (default StorageClass)
    persistence:
      defaultClass: true # Make Longhorn default SC
      defaultClassReplicaCount: 2

    # CSI (scale replicas to 2 for small cluster; saves resources)
    csi:
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 2

    # Manager/Engine (minimal replicas)
    longhornManager:
      replicaCount: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    longhornEngine:
      replicaCount: 2

    # UI (optional but useful; enable if needed)
    longhornUI:
      replicaCount: 2
