apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-video-streamer
  namespace: discord-video-streamer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: discord-video-streamer
  template:
    metadata:
      labels:
        pod: discord-video-streamer
    spec:
      containers:
        - image: ghcr.io/git-saj/discord-video-streamer:latest@sha256:7b043b18a7263acdc59d58d18b13f1c75a9a39aafda2fc2ded5e5d8a8ee5d7a6 # {"$imagepolicy": "flux-system:discord-video-streamer"}
          name: discord-video-streamer
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /app/config.json
              name: config-volume
              subPath: config.json
              readOnly: true
      volumes:
        - name: config-volume
          secret:
            secretName: discord-video-streamer-config
