apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: podinfo
      version: ">=6.8.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
  releaseName: podinfo
  targetNamespace: platform-podinfo
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
    filters:
      - name: grpc # excluded grpc test, due to rpi incompatible
        exclude: true
  driftDetection:
    mode: warn
