# Istio Base (CRDs and base config)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: base
      version: "1.26.2"
      sourceRef:
        kind: HelmRepository
        name: istio
  targetNamespace: istio-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

# Istiod (Control Plane)
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: "1.26.2"
      sourceRef:
        kind: HelmRepository
        name: istio
  targetNamespace: istio-system
  values:
    global:
      multiCluster: false
      meshID: mesh1
      network: network1
    pilot:
      cni:
        enabled: true # For Cilium compatibility with sidecars
      autoscaleEnabled: true
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    meshConfig:
      enableAutoMtls: true
      defaultConfig:
        proxyMetadata:
          ISTIO_META_CNI_ENABLED: "true"

# Gateways (Internal and External)
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateways
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: gateway
      version: "1.26.2"
      sourceRef:
        kind: HelmRepository
        name: istio
  targetNamespace: istio-system
  values:
    gateways:
      istio-ingressgateway-internal:
        name: internal-ingressgateway
        service:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/address-pool: internal-pool
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      istio-ingressgateway-external:
        name: external-ingressgateway
        service:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/address-pool: internal-pool
          externalTrafficPolicy: Local
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
