apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: ">=34.4.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-system
  values:
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: ["web"]
    ports:
      web:
        port: 80
        exposedPort: 80
      websecure:
        port: 443
        exposedPort: 443
    service:
      type: LoadBalancer
    logs:
      general:
        level: INFO
