apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - _base/git
  - _base/helm
  - namespace.yaml
  - kustomization-gateway-api.yaml
  - release-istio.yaml
  - release-metallb.yaml
  - release-cert-manager.yaml
