apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 10m
  path: "./config/crd/standard"
  prune: true #
  sourceRef:
    kind: GitRepository
    name: gateway-api
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: gateways.gateway.networking.k8s.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: httproute.gateway.networking.k8s.io
