apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-device-plugin
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: nvidia-k8s-device-plugin
  path: "./deployments/static"
  prune: true
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: nvidia-device-plugin-daemonset
      namespace: kube-system
