apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-api-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: go-media-control-system
