apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: ">=0.21.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
  releaseName: cnpg
  targetNamespace: cnpg-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: warn
  values:
    # Operator configuration
    operator:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # Monitoring and observability
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: false # Enable if you have Prometheus

    # Security
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
