apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: gpu-operator
      version: ">=25.3.2"
      sourceRef:
        kind: HelmRepository
        name: nvidia
  releaseName: gpu-operator
  targetNamespace: gpu-operator-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: warn
  values:
    toolkit:
      env:
        - name: CONTAINERD_CONFIG
          value: /var/lib/rancher/rke2/agent/etc/containerd/config.toml
        - name: CONTAINERD_SOCKET
          value: /run/k3s/containerd/containerd.sock
        - name: CONTAINERD_RUNTIME_CLASS
          value: nvidia
        - name: CONTAINERD_SET_AS_DEFAULT
          value: "true"
    devicePlugin:
      config:
        name: nvidia-time-slicing-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-time-slicing-config
  namespace: gpu-operator-system
data:
  any: |-
    version: v1
    sharing:
      timeSlicing:
        renameByDefault: false
        failRequestsGreaterThanOne: false
        resources:
          - name: nvidia.com/gpu
            replicas: 4
