apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: cert-manager
      version: ">=1.18.2"
      sourceRef:
        kind: HelmRepository
        name: jetstack
  releaseName: cert-manager
  targetNamespace: cert-manager-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: warn
  values:
    crds:
      enabled: true
